load STM32F401RETx 
project name STCubeGenerated 
project toolchain "MDK-ARM V5" 
project path "C:\Users\aaron\Desktop\2023 - 2024\IOT Systems Advanced\STM32CubeExpansion_NFC5_V2.0.0\Projects\STM32F401RE-Nucleo\Applications\PollingTagDetect\MDK-ARM\RTE\Device\STM32F401RETx\" 
set tpl_path "C:\Users\aaron\AppData\Local\Arm\Packs\Keil\STM32F4xx_DFP\2.17.1\MDK\CubeMX" 
set dest_path "STM32F401RETx" 
SetCopyLibrary  "copy as reference"
